### ISSUE TITLE
Add docs re modprobe blacklist on linux

### ISSUE THREAD

**Issue by markreid** [pokusew/node-pcsclite#10]
Hey @pokusew I ran into a small gotcha trying to use your library (actually nfc-pcsc) on a Raspberry Pi Zero running Raspbian OS. I found [this blog post](https://choffee.co.uk/posts/2015/01/nfc_reader_acr122_linux/) and adding the blacklist items to modprobe solved my issue. Thought you might consider adding a link to the docs from your readme.

Thanks for the library :)

**Comment by pokusew** [comment]
Hi @markreid,

thank you very much. I will definitely add the link to the README.
