### ISSUE TITLE
Cannot install on Windows 10 x64 with Node.js 6.11.2

### ISSUE THREAD

**Issue by vsdigitall** [pokusew/node-pcsclite#12]
**Hello, I receive the following message when trying to install your moduel (npm install nfc-pcsc):**

598 silly install printInstalled
599 verbose stack Error: @pokusew/pcsclite@0.4.17 install: `node-gyp rebuild`
599 verbose stack Exit status 1
599 verbose stack     at EventEmitter.<anonymous> (C:\job\node\node_modules\npm\lib\utils\lifecycle.js:255:16)
599 verbose stack     at emitTwo (events.js:106:13)
599 verbose stack     at EventEmitter.emit (events.js:191:7)
599 verbose stack     at ChildProcess.<anonymous> (C:\job\node\node_modules\npm\lib\utils\spawn.js:40:14)
599 verbose stack     at emitTwo (events.js:106:13)
599 verbose stack     at ChildProcess.emit (events.js:191:7)
599 verbose stack     at maybeClose (internal/child_process.js:891:16)
599 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
600 verbose pkgid @pokusew/pcsclite@0.4.17
601 verbose cwd C:\job\node
602 error Windows_NT 10.0.15063
603 error argv "C:\\job\\node\\node.exe" "C:\\job\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "nfc-pcsc"
604 error node v6.11.2
605 error npm  v3.10.10
606 error code ELIFECYCLE
607 error @pokusew/pcsclite@0.4.17 install: `node-gyp rebuild`
607 error Exit status 1
608 error Failed at the @pokusew/pcsclite@0.4.17 install script 'node-gyp rebuild'.
608 error Make sure you have the latest version of node.js and npm installed.
608 error If you do, this is most likely a problem with the @pokusew/pcsclite package,
608 error not with npm itself.
608 error Tell the author that this fails on your system:
608 error     node-gyp rebuild
608 error You can get information on how to open an issue for this project with:
608 error     npm bugs @pokusew/pcsclite
608 error Or if that isn't available, you can get their info via:
608 error     npm owner ls @pokusew/pcsclite
608 error There is likely additional logging output above.
609 verbose exit [ 1, true ]

**Can you please suggest me how to fix that and install your module.**

**Comment by pokusew** [comment]
Hi @vsdigitall,

I think, it is caused by missing required system dependencies for building this library.

Because this library uses **Node Native Modules**, which are **being built** (using node-gyp) **when installing** _(fyi I don't provide prebuilt binaries, because it brings more problems than it solves)_, you need to have installed **Python 2.7 and some Visual Studio C++ build tools**, as described [in node-gyp's installation guide for Windows](https://github.com/nodejs/node-gyp#on-windows).

You can install all the required tools and configurations with Microsoft's [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) using `npm install --global --production windows-build-tools` from an **elevated** PowerShell or CMD.exe (**run as Administrator**) as described in [Option 1 of node-gyp's guide](https://github.com/nodejs/node-gyp#option-1).

**After that, you can run `npm install nfc-pcsc`, and it should be installed without any problems.**

_If not, try restart computer to allow the changes made during windows-build-tools installation to be correctly propagated._

---

I think, that adding note about these required dependencies would be worthwhile. So, I definitely add more info about it in the docs.

Hope it helps.

**Comment by bincheng68** [comment]
Hi @pokusew 

I run into simular issue with 32 bit Window 10 env. I installed Python2.7.14, then node-gym and Visual studio 2017 community version. But it seems like I could't build lib pcsclite, it complained that the file "build\pcsclite.vcxproj" doesn't exist after it built at least "addon.cpp  pcsclite.cpp cardreader.cpp win_delay_load_hook.cc" four files. Later I noticed this page, I took your "Option 1" soultion, tried to solve this, I successfully installed "windows-build-tools@1.3.2", but after I run "npm install nfc-pcsc" again, the error message was the same :(
Would you mind to take look what went wrong please:

... ...
  addon.cpp
  pcsclite.cpp
d:\jss\node_modules\@pokusew\pcsclite\src\common.h(34): warning C4477: '_snprintf' : format string '%s' requires an argument of type 'char *', but variadic argument 2 has type 'LPVOID' (compiling source file ..\src\pcsclite.cpp) [D:\JSs\node_modules\@pokusew\pcsclite\build\pcsclite.vcxproj]
  cardreader.cpp
  win_delay_load_hook.cc
d:\jss\node_modules\@pokusew\pcsclite\src\common.h(34): warning C4477: '_snprintf' : format string '%s' requires an argument of type 'char *', but variadic argument 2 has type 'LPVOID' (compiling source file ..\src\cardreader.cpp) [D:\JSs\node_modules\@pokusew\pcsclite\build\pcsclite.vcxproj]
C:\Users\Administrator\.node-gyp\8.9.1\ia32\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0
x1F12B0 [D:\JSs\node_modules\@pokusew\pcsclite\build\pcsclite.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\JSs\node_modules\@pokusew\pcsclite
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN jss@1.0.0 No description
npm WARN jss@1.0.0 No repository field.

**Comment by pokusew** [comment]
Hi @bincheng68,

it seems that it is the same (or at least similar) issue as described in https://github.com/oracle/node-oracledb/issues/280 or perhaps in https://github.com/electron/electron-rebuild/issues/163.

I suggest that you follow this [quide](https://github.com/oracle/node-oracledb/issues/280#issuecomment-157272064). According to it, the following could help:

* **delete folder** `C:\Users\Administrator.node-gyp\`
* try again running `npm install nfc-pcsc`

If it does't solve the issue, you could try another steps mentioned in that [quide](https://github.com/oracle/node-oracledb/issues/280#issuecomment-157272064).

Please let me know, if it works for you.
I am available for chat here https://discord.gg/bg3yazg.

Hope it helps.

---

PS Don't forget to star ⭐️ my [nfc-pcsc](https://github.com/pokusew/nfc-pcsc) library, if you find it useful. 😃 Thanks.

**Comment by bincheng68** [comment]
Thank you @pokusew , it's working now :)
