### ISSUE TITLE
Allow protocol 0

### ISSUE THREAD

**Issue by boris-savic** [pokusew/node-pcsclite#7]
Hi,

thanks for pointing me to your fork, regarding Smart Card Resource Manager not running errors that I encountered in Windows. It seems to work now. 

However, the original library allows me to perform DIRECT connection to the reader for perhipherals control. The requirements are following: SCARD_SHARE_DIRECT for mode and 0 for protocol. 

Now your fork overrides protocol 0 in https://github.com/pokusew/node-pcsclite/blob/master/lib/pcsclite.js#L117

I propose to merge from original repo so that the changes in https://github.com/santigimeno/node-pcsclite/blob/master/lib/pcsclite.js#L92 are in effect. 

Boris

**Comment by pokusew** [comment]
Hi @boris-savic 

Thank you for your proposal.
I merged the proposed changes into my fork and released new version [0.4.17](https://github.com/pokusew/node-pcsclite/releases/tag/v0.4.17) to npm.
Now my fork includes all the features from the original library and on top of that it fixes the errors on Windows.

I would like to recommend you my another library for working with NFC.
Take a look at [nfc-pcsc](https://github.com/pokusew/nfc-pcsc). It offers easy to use high level API for detecting, reading and writing NFC tags and cards, also supports Promises and sync/await.

Hope it helps.
